##################################################################
# Compile cenviron.c into cenviron.dll--a shareable object file
# on Cygwin, which is loaded dynamically when first imported.
##################################################################

PYLIB = /usr/include/x86_64-linux-gnu/python3.8
PYINC = /usr/include/python3.8

cenviron.so: cenviron.c
	gcc cenviron.c -g -I$(PYINC) -shared  -L$(PYLIB) -lpython3.8 -o $@ -fPIC
clean:
	rm -f *.pyc cenviron.so
