#!/usr/bin/env python3
# print(sum(int(line) for line in [1, 5, 6]))

# for x in range(1000000): print (x)
# import sys
# print(sys.argv)
# while [1,2,3]: print (True)
# def getopts(argv):
#     opts = {}
#     while argv:
#
#         if argv[0][0] == '-':
#             opts[argv[0]] = argv[1]
#             argv = argv[2:]
#         else:
#             print(argv)
#             argv = argv[1:]
#     return opts
#
#
# if __name__ == '__main__':
#     from sys import argv
#
#     myargs = getopts(argv)
#     if '-i' in myargs:
#         print(myargs['-i'])
#     print(myargs)
# import timeit
# import math
#
#
# def prime_numbers(n):
#     for x in range(2, round(math.sqrt(n) + 1)):
#         if n % x == 0:
#             return False
#     return True


# prime_numbers = prime_numbers(857)
# print(prime_numbers)
# print(f"my version", timeit.timeit(sieve_of_eratosthenes, number=10000))
# print(f"geek", timeit.timeit(SieveOfEratosthenes, number=10000))
# import sys
#
# stdin_fileno = sys.s